# Generated by Django 6.0.5 on 2026-05-21 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='service_categories',
            field=models.ManyToManyField(blank=True, related_name='professional_profiles', to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='professional_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='accounts.professionalprofile'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='professional_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='accounts.professionalprofile'),
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='professional_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='accounts.professionalprofile'),
        ),
        migrations.AddField(
            model_name='review',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='professional_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.professionalprofile'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('client', 'professional_profile'), name='unique_favorite_professional_per_client'),
        ),
        migrations.AddConstraint(
            model_name='availabilityslot',
            constraint=models.UniqueConstraint(fields=('professional_profile', 'day_of_week', 'start_time', 'end_time'), name='unique_availability_slot_per_professional'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('client', 'professional_profile'), name='unique_review_per_client_professional'),
        ),
    ]
